name: Deploy React App to VPS

on:
  push:
    branches:
      - main  # oder 'Development', je nach Branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-react-app .

      - name: Save Docker image as tar
        run: docker save my-react-app -o my-react-app.tar

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "my-react-app.tar"
          target: "~/my-react-app.tar"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker load -i ~/my-react-app.tar
            docker stop my-react-app || true
            docker rm my-react-app || true
            docker run -d -p 3000:80 --name my-react-app my-react-app
